### ISSUE TITLE
Confirm what the protocol should use to ID for a Release

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#26]
Release has the following fields to ID

https://github.com/originalworks/protocol/blame/36892e0f7208f34322b868de445e2d6f5e514dfa/DDEX_messages/ERN_example.xml#L39-L50C25

@revelator-labs can you please confirm which ones we would use as unique?

**Comment by revelator-labs** [comment]
@criadoperez I am not convinced we need to uniquely identify the release, as the unique records we are identifying are: 

- `Registrations` (Lets consider that term for the OW record of a unique ISWC/ISRC+territory+RightType)
- Licenses tied to those `registrations`

The face that an ISWC and ISRC exists in a release is useful data, but a single identifier for a release might not be required if we specify to rights holders to always include the same identifier if they are sending messages about assets that have already been registered. Correct?

I think the protocol should store all the release identifiers in any case in order to map the release metadata (cover art, upc, Grid, etc...) to the OW `Registrations`.

The registry should look up any identifier or title of a release and map that to all the `registrations` by [serch_term]->[indexed ISRC metadata]-> [return all releases containing search_term] = {all ISRCs in that release} + {All ISWCs connected to those ISRCs} + {array of all public metadata per release}

**Comment by criadoperez** [comment]
Ok. So we are saying the won't be one unique way to identify a release, but multiple ways. 

So for example one user could use the `GlobalReleaseId`, another the `EAN` and another the  `UPC`, and are valid ways to uniquely identify that release.

**Comment by criadoperez** [comment]
We concluded we will identify a Release by two columns, instead of one.

So we will have a `ReleaseIDField` that can be any of the 4 values:

```xml
            <ReleaseId>
                <ProprietaryId>REL12345</ProprietaryId>
                <GlobalReleaseId>GRid::G123456789012345678</GlobalReleaseId>
                <ICPN>1234567890123</ICPN>
                <CatalogNumber>CAT12345</CatalogNumber>
            </ReleaseId>
```

And ReleaseIDValue that will contain the value of that ReleaseID column.

So for example: `ReleaseIDField=ICPN` and `ReleaseIDValue=1234567890123`
