### ISSUE TITLE
Allow upload file of Financial factsheet

### ISSUE THREAD

**Issue by criadoperez** [originalworks/protocol#9]
Payments providers should be able to inform the protocol of the offchain revenue reported about a specific asset.

In order to validate the financial history, the Indentura pool will need to validate the revenue history based on the xml data in the CID provided by Revelator. 

The XML file needs to be a [DSR message](https://github.com/originalworks/protocol/blob/main/DDEX_messages/DSR_example.xml)

The protocl should validate the DSR message so Indentura can trust the data.

**Comment by revelator-labs** [comment]
@criadoperez - I agree that for the protocol we should stick to ddex messages, but in the use case of connecting to the Indentura pools, I think we can use the infrastructure that we have on v0.1 to roll out the advance feature on the registry.

**Comment by criadoperez** [comment]
ok. But if I understand correctly, the proposed json file doesn't exist either. Meaning that generating the json above or a ddex compliant xml is the same effort for us no? Or am I missing something?

**Comment by revelator-labs** [comment]
@criadoperez we've agreed to use the DSR message. Additionally since the protocl will validate, the lending pool will be able to trust the data and read the values directly from the message posted to the unique CID. See the updated ticket.

@0xbarath / @criadoperez We need to make these statements also private and validated with ZK proofs in the long term, but for now we should define if the protocol will store any of this data in our "virtual dbs" or just expose the CID to Indentura via the Registry whenever a wallet connected - i.e. scanning our specific financial "Data channel" of CIDs for any messages about that asset - allowing the lending pool to read it.
